# Generated by Django 4.1.1 on 2022-09-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/user/user-profile.png', upload_to='user-img'),
        ),
    ]
